### Load the data

In [18]:
import pandas as pd
import json

# Load CSV
df = pd.read_csv("../datasets/USvideos.csv")


# Load JSON to map category_id to category name
with open("../datasets/US_category_id.json") as f:
    category_data = json.load(f)

category_mapping = {
    int(item["id"]): item["snippet"]["title"]
    for item in category_data["items"]
}

# Add readable category
df["category"] = df["category_id"].map(category_mapping)

In [19]:
df.head(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,category
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,People & Blogs
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",Entertainment
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,Comedy
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,Entertainment
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,Entertainment

### Clean and format data

In [21]:
df['publish_time'] = pd.to_datetime(df['publish_time'])
df['trending_date'] = pd.to_datetime(df['trending_date'], format='%y.%d.%m')

df.drop_duplicates(subset=['video_id', 'trending_date'], inplace=True)

df.dropna(inplace=True)

### Explore DataFrame

In [22]:
print(df.shape)
print(df.columns)
df.info()
df.describe()

(40330, 17)
Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'category'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
Index: 40330 entries, 0 to 40948
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40330 non-null  object
 1   trending_date           40330 non-null  datetime64[ns]
 2   title                   40330 non-null  object
 3   channel_title           40330 non-null  object
 4   category_id             40330 non-null  int64
 5   publish_time            40330 non-null  datetime64[ns, UTC]
 6   tags                    40330 non-null  object
 7   views                   40330 non-null  int64
 8   likes                   40330 non-null  int64
 9   dislikes                40330 non-null  int64
 10  comment_count           40330 non-null  int64
 11  thumbnail_link          40330 non-null  object
 12  comments_disabled       40330 non-null  bool
 13  ratings_disabled        40330 non-null  bool
 14  video_error_or_removed  40330 non-null  bool
 15  description             40330 non-null  object
 16  category                40330 non-null  object
dtypes: bool(3), datetime64[ns, UTC](1), datetime64[ns](1), int64(5), object(7)
memory usage: 4.7+ MB

,trending_date,category_id,views,likes,dislikes,comment_count
count,40330,40330.000000,4.033000e+04,4.033000e+04,4.033000e+04,4.033000e+04
mean,2018-02-27 09:58:12.526654976,19.942276,2.370795e+06,7.462101e+04,3.508275e+03,8.289024e+03
min,2017-11-14 00:00:00,1.000000,5.490000e+02,0.000000e+00,0.000000e+00,0.000000e+00
25%,2018-01-04 00:00:00,17.000000,2.466270e+05,5.616000e+03,2.040000e+02,6.230000e+02
50%,2018-02-26 00:00:00,24.000000,6.882900e+05,1.835150e+04,6.355000e+02,1.873000e+03
75%,2018-04-24 00:00:00,25.000000,1.831572e+06,5.562550e+04,1.945750e+03,5.784750e+03
max,2018-06-14 00:00:00,43.000000,2.252119e+08,5.613827e+06,1.643059e+06,1.228655e+06
std,NaN,7.596013,7.432303e+06,2.297357e+05,2.318831e+04,3.433567e+04